
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: 123789

development:
  <<: *default
  database: friending_db

test:
  <<: *default
  database: db/friending_db

production:
  <<: *default
  database: db/friending_db
